"""Bit-exact verification against .NET 9 System.Random.

Compares the Python port (sim/rng.py) to test vectors generated by
tools/RngOracle/ (a .NET 9 console app). The oracle JSON is committed
so the test runs without requiring the .NET SDK on CI.

Schema is documented at the top of tools/RngOracle/Program.cs.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from sim.rng import (
    DotNetSeededRandom,
    Rng,
    get_deterministic_hash_code,
)

ORACLE_PATH = Path(__file__).resolve().parent.parent / "tools" / "RngOracle" / "oracle.json"


@pytest.fixture(scope="module")
def oracle():
    if not ORACLE_PATH.exists():
        pytest.skip(f"Oracle JSON missing: regenerate with "
                    f"`dotnet run --project tools/RngOracle/RngOracle.csproj`")
    return json.loads(ORACLE_PATH.read_text(encoding="utf-8-sig"))


def test_deterministic_hash_matches_dotnet(oracle):
    for name, expected in oracle["deterministicHash"].items():
        assert get_deterministic_hash_code(name) == expected, name


@pytest.mark.parametrize("seed_str", ["0", "1", "42", "-1", "2147483647", "-2147483648", "-559038737"])
def test_next_double_matches_dotnet(oracle, seed_str):
    seed = int(seed_str)
    expected = oracle["nextDouble"][seed_str]
    r = DotNetSeededRandom(seed)
    actual = [r.next_double() for _ in range(len(expected))]
    assert actual == expected, f"first mismatch at index " \
        f"{next(i for i, (a, b) in enumerate(zip(actual, expected)) if a != b)}"


@pytest.mark.parametrize("seed_str", ["0", "1", "42", "-1", "2147483647", "-2147483648", "-559038737"])
@pytest.mark.parametrize("max_str", ["2", "6", "13", "100", "1000"])
def test_next_int_matches_dotnet(oracle, seed_str, max_str):
    seed = int(seed_str)
    max_exclusive = int(max_str)
    expected = oracle["nextInt"][seed_str][max_str]
    r = DotNetSeededRandom(seed)
    actual = [r.next_max(max_exclusive) for _ in range(len(expected))]
    assert actual == expected


@pytest.mark.parametrize("seed_str", ["0", "1", "42", "-1", "-559038737"])
def test_next_bytes_matches_dotnet(oracle, seed_str):
    seed = int(seed_str)
    expected = bytes(oracle["nextBytes"][seed_str])
    r = DotNetSeededRandom(seed)
    actual = r.next_bytes(len(expected))
    assert actual == expected


@pytest.mark.parametrize("seed", [0, 1, 42, -1, 2147483647, -559038737])
def test_seeded_rng_matches_game_layer(oracle, seed):
    """For each (seed, category), the Python `Rng(seed, name)` must produce
    the same NextDouble stream as `new System.Random((int)(uint(seed) + uint(hash(name))))`.
    This is the exact path the game uses to build per-category RNGs.
    """
    for cat in oracle["deterministicHash"]:
        key = f"{seed}:{cat}"
        expected = oracle["seededRng"][key]
        r = Rng(seed & 0xFFFFFFFF, cat)
        actual = [r.next_float() for _ in range(len(expected))]
        assert actual == expected, f"mismatch on {key}"
